document.addEventListener('DOMContentLoaded',()=>{
 const video=document.querySelector('.field video'), field=document.querySelector('.field'), messages=document.querySelector('#messages');
 if(!video||!field||!messages)return;
 const ui=document.createElement('div');ui.className='video-ui';ui.innerHTML='<button id="videoToggle">❚❚</button><span>NEURAL VISUALIZER · <b id="videoState">IDLE</b></span>';field.appendChild(ui);
 const overlay=document.createElement('div');overlay.className='answer-overlay';overlay.innerHTML='<span>QWEN LOCAL</span><p>Aguardando sua pergunta.</p>';field.appendChild(overlay);
 const css=document.createElement('style');css.textContent='.video-ui{position:absolute;left:16px;right:16px;bottom:14px;display:flex;gap:10px;z-index:3;font:10px DM Mono;color:#9dd6d2;letter-spacing:.08em}.video-ui button{background:#06161a;border:1px solid #42777a;color:#b8f5ed;border-radius:4px;width:30px;height:26px}.answer-overlay{position:absolute;right:18px;top:18px;z-index:3;max-width:280px;padding:10px 12px;border-left:2px solid #67e8f9;background:rgba(4,18,22,.82);backdrop-filter:blur(6px)}.answer-overlay span{font:9px DM Mono;color:#67e8f9}.answer-overlay p{font-size:12px;line-height:1.35;margin:5px 0;color:#d8f3f2}.field.neural-working video{filter:saturate(1.8) brightness(1.15);opacity:.9}.field.neural-success video{filter:saturate(1.7) hue-rotate(55deg)}';document.head.appendChild(css);
 document.querySelector('#videoToggle').onclick=()=>{if(video.paused){video.play();document.querySelector('#videoToggle').textContent='❚❚'}else{video.pause();document.querySelector('#videoToggle').textContent='▶'}};
 field.addEventListener('click',e=>{if(e.target.closest('button'))return;video.currentTime=(video.currentTime+2)%(video.duration||10);video.play()});
 new MutationObserver(()=>{const last=messages.lastElementChild;if(!last)return;const p=last.querySelector('p');if(last.classList.contains('user')){field.classList.add('neural-working');field.classList.remove('neural-success');document.querySelector('#videoState').textContent='PROCESSING';overlay.querySelector('p').textContent='O Qwen está analisando…'}else if(last.classList.contains('bot')){field.classList.remove('neural-working');field.classList.add('neural-success');document.querySelector('#videoState').textContent='RESPONSE READY';overlay.querySelector('p').innerHTML=p?.innerHTML||''}else{field.classList.remove('neural-working');document.querySelector('#videoState').textContent='OFFLINE'}}).observe(messages,{childList:true});
});
